### PR TITLE
OSH Park drill fixes

### PR DESCRIPTION
**Pull request by dwhinham**
Hi marqs,

You are probably already aware of this, and I'm not sure if you would want to apply this to mainline as it may affect other PCB fabricators, but I thought I'd share my experience with the PCB and OSH Park in case you wanted to add it to a branch, or as a "contrib", or whatever you think is best.

Alternatively, I am happy to maintain a fork.
I think this will help a lot of DIYers that like to use OSH Park.

Commit message:
~~~ 
When submitting the board to OSH Park (a popular hobbyist-friendly PCB
fabrication service), two issues are present with the OSSC PCB:

 1. It contains plated slots (for the power and audio jacks, and the
    component video connector). These *are* supported by OSH Park, but
    lines must be added to the Edge.Cuts layer so that they are milled
    out properly. Otherwise, a hole will just be drilled at the start of
    the slot, and the rest of the slot will not be cut out.

    OSH Park's upload system detects and warns users of this issue.

    See: http://docs.oshpark.com/submitting-orders/cutouts-and-slots/
         https://hackaday.io/page/1224-plated-slots-for-oshpark-in-kicad

 2. The holes for the audio ADC's oscillator are too small after being
    plated, so the leads of the oscillator won't fit through.

This commit provides fixes for both these issues, and a small run has
been successfully produced by OSH Park and assembled by myself.

I have seen other patches for issue 1, but they replace the slots with
larger holes. This patch results in plated slots as originally intended.
~~~

**Before** this patch:
slots
oscillator

**After** this patch:
slots2
oscillator2

(The mis-produced boards were not wasted - I own a Dremel drill press and was easily able to widen the slots and successfully assemble them 😃)

Cheers! 😃

### CODE REVIEW

**Comment by marqs85** [comment]
Thanks for running v1.6 through OSHPark - you're probably the first one to do that. The earlier revisions which had been prototyped via them did not have plated slots, so I understand they may need some additional markings (1).

As for (2), did you use ECS-245.7-18-9X oscillator? That part fit into the preassembled prototypes I got so I'm a bit surprised if there was an issue with OSHPark. Lead / hole diameters are 0.32mm and 0.4mm respectively, but maybe plating slightly reduces the effective size. It should be okay to extend them a bit anyway as long as spacing / annular ring rules are not violated.

**Comment by dwhinham** [comment]
My pleasure! This was the first time I've ever actually ordered a PCB for a project or built something this advanced, which is why I didn't really understand the drilling caveats for the first batch. It's been a great learning experience 😃 

Yes, I used the exact item specified on the BOM and ordered from Mouser:
img_20170702_204538

According to the [OSH Park drill specs](http://docs.oshpark.com/submitting-orders/drill-specs/), after plating the hole should be +/- 2.5 mil (0.0635mm), which in theory should take our 0.4mm hole down to 0.3365mm in the worst case scenario - still large enough for our 0.32mm lead. But for some reason, in reality it was too small. I'm not sure if the drill was too small or if the plating was too thick, but either way, the 0.5mm hole worked well on my second batch.

Here's a photo of the underside of the 0.5mm board showing the leads of the oscillator. The nearby traces and pads seem to be fine with the increased size - perhaps if there are any other drill sizes between 0.4-0.5mm a slightly smaller one could be tried:
img_20170702_210549

**Comment by marqs85** [comment]
I merged the patch but changed ECS-3X9X pad diameter to 0.9mm in order to fulfill 7mil (~0.18mm) annular ring design rule.

**Comment by dwhinham** [comment]
Awesome, thanks! 😄

**Pull request merged**
